// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPlMPJHY7l-77qUKd9pWGcFqfUGvGky8I',
    appId: '1:369726482784:web:6e1b2f7f42a6d34f1a1605',
    messagingSenderId: '369726482784',
    projectId: 'grad-app-96513',
    authDomain: 'grad-app-96513.firebaseapp.com',
    databaseURL: 'https://grad-app-96513-default-rtdb.firebaseio.com',
    storageBucket: 'grad-app-96513.appspot.com',
    measurementId: 'G-82Q4VSJSFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP6U3rJSJm3jj41erowYYTStBIlzxrZVs',
    appId: '1:369726482784:android:b86c71b10a9369951a1605',
    messagingSenderId: '369726482784',
    projectId: 'grad-app-96513',
    databaseURL: 'https://grad-app-96513-default-rtdb.firebaseio.com',
    storageBucket: 'grad-app-96513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhzhPkyKu_fRn7g3dlB9PZFXUzm9ORdHY',
    appId: '1:369726482784:ios:5b757e93a41d35791a1605',
    messagingSenderId: '369726482784',
    projectId: 'grad-app-96513',
    databaseURL: 'https://grad-app-96513-default-rtdb.firebaseio.com',
    storageBucket: 'grad-app-96513.appspot.com',
    iosBundleId: 'com.example.grad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhzhPkyKu_fRn7g3dlB9PZFXUzm9ORdHY',
    appId: '1:369726482784:ios:70230139f4b1e1071a1605',
    messagingSenderId: '369726482784',
    projectId: 'grad-app-96513',
    databaseURL: 'https://grad-app-96513-default-rtdb.firebaseio.com',
    storageBucket: 'grad-app-96513.appspot.com',
    iosBundleId: 'com.example.grad.RunnerTests',
  );
}
